//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gepdm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMT_ANAGART
    {
        public int ID { get; set; }
        public string IDEXPORT { get; set; }
        public string CODART { get; set; }
        public string DESCART { get; set; }
        public string DESCARTEST { get; set; }
        public string UM1 { get; set; }
        public string CODFAM { get; set; }
        public string DESCFAM { get; set; }
        public string CODSFAM { get; set; }
        public string DESCSFAM { get; set; }
        public string CODGRUPPO { get; set; }
        public string DESCGRUPPO { get; set; }
        public string CODSGRUPPO { get; set; }
        public string DESCSGRUPPO { get; set; }
        public string CODPROV { get; set; }
        public string CODTIPOPROD { get; set; }
        public string CODREP { get; set; }
        public string USEREXPORT { get; set; }
        public Nullable<int> FLGIMPORT { get; set; }
        public Nullable<int> FLGVALIDATE { get; set; }
    }
}
