//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gepdm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMT_DIBA
    {
        public int ID { get; set; }
        public string IDEXPORT { get; set; }
        public string CODPROG { get; set; }
        public string CODPADRE { get; set; }
        public string CODFIGLIO { get; set; }
        public decimal QTA { get; set; }
        public string TREEDEPTH { get; set; }
        public string LEVEL { get; set; }
        public string USEREXPORT { get; set; }
        public int FLGIMPORT { get; set; }
        public int FLGVALIDATE { get; set; }
    }
}
